-- AlterEnum
ALTER TYPE "ReminderType" ADD VALUE 'REASSIGNED';
ALTER TYPE "ReminderType" ADD VALUE 'DUE_DATE_CHANGED';
ALTER TYPE "ReminderType" ADD VALUE 'STATUS_CHANGED';
ALTER TYPE "ReminderType" ADD VALUE 'PRIORITY_CHANGED';
