-- NEUTRALIZED 2026-06-28.
--
-- This migration originally TRUNCATEd all operational tables and deleted
-- non-admin users. That is destructive and unsafe to run on any environment
-- that has not applied it yet (a prod DB that is behind on migrations would
-- lose data on the next `migrate deploy`).
--
-- Operational-data resets are now done with a repeatable, dry-run-by-default
-- script instead of a migration:
--   pnpm --filter api db:clean         (preview)
--   pnpm --filter api db:clean:force   (delete)
--
-- The body is intentionally a no-op so this migration is harmless wherever it
-- has not yet run, while remaining present in history for environments that
-- already applied the original.
SELECT 1;
